### ISSUE TITLE
Object destruction should have a common method name

### ISSUE THREAD

**Issue by zombiezen** [adam000/Go-SDL2#17]
There are lots of objects in SDL that need manual destruction.  We're pretty inconsistent about our naming, which could prevent us from writing an interface.  I'm not suggesting we define this interface.

Possibilities:
- `Close() error` -- this should be preferred if destructions can generally fail.
- `Free()` -- a little too C-ish for my taste.
- `Release()` -- reads pretty clearly, is different enough from Close that it implies different semantics
- `Destroy()` -- very C++ like

**Comment by adam000** [comment]
As we discussed out of band, I like `Destroy()` the best because it has finality and suggests that you can't use the resource after calling it.

**Comment by zombiezen** [comment]
Cool.  I'll start refactoring and see if I need the `error` return type.
